### ISSUE TITLE
Songs end/skip

### ISSUE THREAD

**Issue by FredxDX** [RainyXeon/ByteBlaze#105]
**Describe the bug**
When ever I play a song no matter if youtube or spotify it skips after around 30 seconds. It does get the duration right and if the song is in a playlist only the first song gets skipped and the rest plays normaly

**To Reproduce**

1. Play song
2. idk skips for me

**Expected behavior**
Doesnt skip/ stop song

**Screenshots and logs (logs file if avalible)**
[ByteBlaze-out.log](https://github.com/RainyXeon/ByteBlaze/files/15440578/ByteBlaze-out.log)
[Lavalink-out.log](https://github.com/RainyXeon/ByteBlaze/files/15440588/Lavalink-out.log)

**Host info: (use `/info status` command and paste here, below is example)**

- OS: Ubuntu 22.04.4 LTS
- CPU: AMD EPYC 7543 32-Core Processor
- Uptime: 3d 20h 8s
- RAM: 32.00 GB
- Memory Usage: 70.6mb/31398.14 (MB)
- Node.js: v18.19.0

**Bot info (use `/info status` command and paste here, below is example):**

- Codename: vocaloid_kaito
- Bot version: 5.2.2+1715871660348
- Autofix version: 5.1.0
- Discord.js: 14.15.2
- Guild Count: 3
- User count: 32

**Comment by RainyXeon** [comment]
@FredxDX it's a myth on lavalink when some track just play 30 second and then skipped immediately. Maybe you can try to set up ipv6 rotation

**Comment by FredxDX** [comment]
Well it seems this has fixed itself yesterday. 
Had the issue for 2 months now and I'm just hoping it wont return
