### ISSUE TITLE
user premium change

### ISSUE THREAD

**Issue by 13LuckyBack** [RainyXeon/ByteBlaze#107]
i think it would be beter that if an bot owner/admin is creating a premium code that instead he sends it in that channel that the bot is sending it to the users his private messages

Also if #106 is going true that if we create a premium key he will send it in the users his private messages

**Comment by RainyXeon** [comment]
@13LuckyBack Now avaliavble on https://github.com/RainyXeon/ByteBlaze/commit/0dc859b58aad749b8f2d7e6c7b81cd357c7633b0
