### ISSUE TITLE
Use Discord's Timestamp instead of normal time text

### ISSUE THREAD

**Issue by NineLEL** [RainyXeon/ByteBlaze#109]
**Enhancement Request:** Use Discord's Unix Timestamp

**Description:**
I suggest using Discord's Unix Timestamp instead of normal text to display the time of an action (e.g., Premium redeem log). Currently, it only shows the server's timezone where the bot is running. For example, I live in Thailand, but my bot is hosted on a US server.

**Example:**
Using a Discord Unix Timestamp like `<t:1717351140:F>` will display as:

- "Monday, June 3, 2024 12:59 AM" for the Asia/Bangkok (GMT+7) timezone
- "Sunday, June 2, 2024 05:59 PM" for the GMT+0 timezone

**Instead of:**
![image](https://github.com/RainyXeon/ByteBlaze/assets/74411437/d60285b0-ec4c-4393-86bc-6c9a5fd27ea7)

**We can try:**
![image](https://github.com/RainyXeon/ByteBlaze/assets/74411437/30428699-65f0-4c1a-b60b-d48948f8e2a8)

**Comment by RainyXeon** [comment]
Now avaliable at dc0cd84a0398642df46ec6950ca510427be2d450
