### ISSUE TITLE
24/7 BUG in more than one bot on same instance.

### ISSUE THREAD

**Issue by longhorn228** [RainyXeon/ByteBlaze#121]
**Describe the bug**
If I'm having more than one bot on the same instance. Example: 3
I run 24/7 for each bot in difference vc and I restart the bot, all the bots will join the vc in which bot 0 is aka the main bot.

**To Reproduce**

1. Enable 24/7 for each bot in a differenct VC.
2. Make sure each bot is in a seperate VC.
3. Restart hte bot.

**Expected behavior**
Bot should join back their respective VCs.

**Comment by RainyXeon** [comment]
#129
