### ISSUE TITLE
Skip Button In Queue/Playlist

### ISSUE THREAD

**Issue by longhorn228** [RainyXeon/ByteBlaze#123]
**Describe the bug**
If you've a playlist example more than one song in the queue and you use the skip button, it will send the error:
https://i.imgur.com/f4VnDJy.png

**To Reproduce**

1. Play a playlist.
2. Use the skip button to skip the song.
3. The bot will skip the song but will send an error in the console.

**Screenshots and logs (logs file if avalible)**
https://i.imgur.com/f4VnDJy.png

**Comment by RainyXeon** [comment]
#129
