### ISSUE TITLE
Rebuilding will stop the 24/7

### ISSUE THREAD

**Issue by longhorn228** [RainyXeon/ByteBlaze#124]
**Describe the bug**
If you rebuild the bot, example using `bash start.sh` then the bot will leave the 24/7 vc after few minutes.

**To Reproduce**

1. Enable 24/7
2. Rebuild the bot.

**Expected behavior**
Shouldn't leave the vc since it s supposed to stasy 24/7

**Comment by RainyXeon** [comment]
#129
