### ISSUE TITLE
Stop button in queue

### ISSUE THREAD

**Issue by longhorn228** [RainyXeon/ByteBlaze#128]
If you play a playlist or if you've more than one song in the playlist, and you use the stop button, it sends this error:
https://i.imgur.com/FmUtPmu.png

**Comment by RainyXeon** [comment]
#129

**Comment by longhorn228** [comment]
So is this an issue because of the multi-bot instance?

**Comment by RainyXeon** [comment]
> So is this an issue because of the multi-bot instance?
Yep, I confirmed that it's have this issue on multi bot. But vice versa with single bot
