### ISSUE TITLE
Multi bot issue related 

### ISSUE THREAD

**Issue by RainyXeon** [RainyXeon/ByteBlaze#129]
**Describe the bug**
This issue will list all issue related to multi bot feature 

**Currently please use 1 bot only!!!!!**

**Comment by longhorn228** [comment]
It happens even with a single instance.

**Comment by RainyXeon** [comment]
I think I have no choice but remove the multi bot feature

**Comment by RainyXeon** [comment]
Because multi bot system is too complex to handle currently, I have to drop support for muilt bot feature sadly in commit https://github.com/RainyXeon/ByteBlaze/commit/0b258d9aedc18fb05a3cb55904a7057555c1c9a6
