### ISSUE TITLE
Bot randomly stops music and leaves vc

### ISSUE THREAD

**Issue by longhorn228** [RainyXeon/ByteBlaze#130]
If you play a lengthy playlist—though the required duration isn't clear—I experimented with several playlists of varying lengths. Each time, the bot randomly exited the voice channel and displayed this error message:

Please note, the bot leave occurs randomly, without any specific song count or time trigger.
https://i.imgur.com/kKbhqvI.png

**Comment by RainyXeon** [comment]
As I can see here, this is from lavalink server instead because the rainlink client execute player exception event. That means something went wrong with lavalink. So in this situation, please check the lavalink server. (Note: Spotify source is not actually from Spotify, it's from yt)

**Comment by longhorn228** [comment]
If I'm not wrong, you seem to be using noedlink right? Could you please share me your nodelink config.js because when I tried nodelink previously, it didn't support a lot of sources.
