### ISSUE TITLE
guild based premium have some trouble when using both user and guild access

### ISSUE THREAD

**Issue by longhorn228** [RainyXeon/ByteBlaze#135]
I just generate a premiun keey.
When I redeemed it as the "guild" option, it did get redeemed but when I tried to run a premium command, it just said "you're not a premium user".

**Comment by RainyXeon** [comment]
Look at this file: https://github.com/RainyXeon/ByteBlaze/blob/dev/src/structures/Command.ts#L5-L13
We can see that there are 2 different accessable for premium is guild and user.
Please chaange to `Accessableby.GuildPremium` in the command if you want your command is only for guild premium
This split is for avoid error in some premium command.

**Comment by longhorn228** [comment]
Yes I know, but what if I want the same command to either be accessable by guildpremium or userpremium? The problem is that even if I redeem a guildpremium key, it still won't let me execute that command. It will still ask me to have userpremium,

**Comment by RainyXeon** [comment]
@longhorn228 Now fixed on https://github.com/RainyXeon/ByteBlaze/commit/2cc897340238e62656e7df46a67ecaa5b6b90a86
