### ISSUE TITLE
Rainlink break when build bot

### ISSUE THREAD

**Issue by tathaha** [RainyXeon/ByteBlaze#138]
**build it and Rainlink just break on every os i know**
"src/rainlink/Node/RainlinkPlayerEvents.ts(32,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(33,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(46,24): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(51,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(62,24): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(67,26): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(68,17): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(83,17): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(85,24): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(96,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(97,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(108,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(109,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(120,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(121,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(134,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkPlayerEvents.ts(138,15): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkTrack.ts(119,13): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkQueue.ts(68,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkQueue.ts(82,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkQueue.ts(92,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkQueue.ts(99,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/VoiceReceiver/Plugin.ts(50,21): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/VoiceReceiver/Plugin.ts(55,21): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/VoiceReceiver/Plugin.ts(61,21): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/VoiceReceiver/Plugin.ts(82,23): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/VoiceReceiver/Plugin.ts(91,23): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/VoiceReceiver/Plugin.ts(118,22): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkFilter.ts(175,25): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(219,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(259,20): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(262,58): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(333,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(352,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(372,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(501,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(502,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(522,33): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(549,10): error TS2339: Property 'removeAllListeners' does not exist on type 'RainlinkPlayer'.
src/rainlink/Player/RainlinkPlayer.ts(578,76): error TS2554: Expected 2 arguments, but got 3.
src/rainlink/Player/RainlinkPlayer.ts(666,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(670,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Player/RainlinkPlayer.ts(708,12): error TS2339: Property 'emit' does not exist on type 'RainlinkPlayer'.
src/rainlink/Player/RainlinkPlayer.ts(712,12): error TS2339: Property 'emit' does not exist on type 'RainlinkPlayer'.
src/rainlink/Player/RainlinkPlayer.ts(726,10): error TS2339: Property 'emit' does not exist on type 'RainlinkPlayer'.
src/rainlink/Drivers/Lavalink4.ts(128,19): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkNode.ts(90,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkNode.ts(129,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkNode.ts(137,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkNode.ts(152,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Node/RainlinkNode.ts(189,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Manager/RainlinkPlayerManager.ts(50,12): error TS2576: Property 'on' does not exist on type 'RainlinkPlayer'. Did you mean to access the static member 'RainlinkPlayer.on' instead?
src/rainlink/Manager/RainlinkPlayerManager.ts(53,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Manager/RainlinkPlayerManager.ts(70,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Manager/RainlinkNodeManager.ts(80,18): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Drivers/Lavalink3.ts(285,19): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Drivers/Nodelink2.ts(164,19): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Rainlink.ts(661,10): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Library/AbstractLibrary.ts(19,19): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/Deezer/Plugin.ts(241,22): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/Apple/Plugin.ts(315,22): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/Nico/Plugin.ts(221,23): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/rainlink/Plugin/PlayerMoved/Plugin.ts(66,19): error TS2339: Property 'emit' does not exist on type 'Rainlink'.
src/structures/PageQueue.ts(115,17): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<StringSelectMenuInteraction<CacheType> | UserSelectMenuInteraction<CacheType> | RoleSelectMenuInteraction<CacheType> | MentionableSelectMenuInteraction<...> | ChannelSelectMenuInteraction<...> | ButtonInteraction<...>>'.
src/structures/PageQueue.ts(208,17): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<StringSelectMenuInteraction<CacheType> | UserSelectMenuInteraction<CacheType> | RoleSelectMenuInteraction<CacheType> | MentionableSelectMenuInteraction<...> | ChannelSelectMenuInteraction<...> | ButtonInteraction<...>>'.
src/structures/PageQueue.ts(293,17): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<StringSelectMenuInteraction<CacheType> | UserSelectMenuInteraction<CacheType> | RoleSelectMenuInteraction<CacheType> | MentionableSelectMenuInteraction<...> | ChannelSelectMenuInteraction<...> | ButtonInteraction<...>>'.
src/structures/PageQueue.ts(385,17): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<StringSelectMenuInteraction<CacheType> | UserSelectMenuInteraction<CacheType> | RoleSelectMenuInteraction<CacheType> | MentionableSelectMenuInteraction<...> | ChannelSelectMenuInteraction<...> | ButtonInteraction<...>>'.
src/structures/PageQueue.ts(469,17): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<StringSelectMenuInteraction<CacheType> | UserSelectMenuInteraction<CacheType> | RoleSelectMenuInteraction<CacheType> | MentionableSelectMenuInteraction<...> | ChannelSelectMenuInteraction<...> | ButtonInteraction<...>>'.
src/commands/Owner/Announcement.ts(86,57): error TS1501: This regular expression flag is only available when targeting 'es2018' or later.
src/commands/Playlist/Delete.ts(123,18): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<StringSelectMenuInteraction<CacheType> | UserSelectMenuInteraction<CacheType> | RoleSelectMenuInteraction<CacheType> | MentionableSelectMenuInteraction<...> | ChannelSelectMenuInteraction<...> | ButtonInteraction<...>>'.
src/structures/Page.ts(91,17): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<StringSelectMenuInteraction<CacheType> | UserSelectMenuInteraction<CacheType> | RoleSelectMenuInteraction<CacheType> | MentionableSelectMenuInteraction<...> | ChannelSelectMenuInteraction<...> | ButtonInteraction<...>>'.
src/structures/Page.ts(162,17): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<StringSelectMenuInteraction<CacheType> | UserSelectMenuInteraction<CacheType> | RoleSelectMenuInteraction<CacheType> | MentionableSelectMenuInteraction<...> | ChannelSelectMenuInteraction<...> | ButtonInteraction<...>>'.
src/events/track/trackStart.ts(251,17): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<ButtonInteraction<"cached">>'.
src/events/track/trackStart.ts(255,23): error TS2339: Property 'removeAllListeners' does not exist on type 'InteractionCollector<StringSelectMenuInteraction<"cached">>'."

**Comment by RainyXeon** [comment]
@tathaha I acknowledged this issue so can u try the patch in dev branch?

**Comment by RainyXeon** [comment]
Now fixed on https://github.com/RainyXeon/ByteBlaze/commit/843c0cfd50b6f0cfe9eb89ce01e33ee45f54c758
