### ISSUE TITLE
Render Hosting Support Because I use to hosting because it use static address it not work with the fastify 

### ISSUE THREAD

**Issue by tathaha** [RainyXeon/ByteBlaze#143]
Is your feature request related to a problem? Please describe.
I'm always frustrated when hosting my application because the hosting service uses a static address, which doesn't work seamlessly with Fastify. This limitation hinders my ability to deploy my Fastify-based application effectively on this hosting platform.

Describe the solution you'd like
I would like support for rendering hosting with static addresses in Fastify. This could involve a mechanism to handle static address configurations or an option to accommodate such setups without breaking the application's functionality.

Describe alternatives you've considered
I've considered using a different hosting service that supports dynamic addresses, but this isn't ideal due to existing infrastructure and cost considerations. Another alternative could be using a reverse proxy, but that adds complexity and overhead.

Additional context
Currently, my hosting provider offers a reliable service, and switching is not a feasible option. Any potential solution would ideally allow me to continue using my existing hosting setup without significant changes to my application architecture.

**Comment by RainyXeon** [comment]
@tathaha Can you tell me more how u config render? LIke I just wanna know

**Comment by tathaha** [comment]
I turned on the web server for the web app after deployment, but it just can't blind the port it says that the port is not open because it only blinds to 127.0.0.1 It can not turn on and always runs 24/7 for the instance. I read in the Fastify doc that I need a reverse proxy to run it and render it like it doesn't have

**Comment by tathaha** [comment]
![image](https://github.com/user-attachments/assets/6328b129-7d51-4108-85e8-89c0f9c1550b)
it's have a problem when deploying

**Comment by RainyXeon** [comment]
@tathaha can u switch to byteblaze/next branch. Bc that's where I apply the patch

**Comment by tathaha** [comment]
I have switched it in my fork dev branch
![image](https://github.com/user-attachments/assets/7f83e30d-78cf-4295-b5a3-915f66373f67)

**Comment by RainyXeon** [comment]
@tathaha Hmm so can u replace all content from `src/web/server.ts` to this patch's [content](https://github.com/RainyXeon/ByteBlaze/blob/byteblaze/next/src/web/server.ts)?

**Comment by tathaha** [comment]
it's work now thank you ❤️
