### ISSUE TITLE
control setup feature

### ISSUE THREAD

**Issue by naiserve** [RainyXeon/ByteBlaze#148]
I want the setup's controls to be the same as the / command with volume up and volume down. What should I do?

**Comment by RainyXeon** [comment]
@naiserve Can u describe it more?

**Comment by naiserve** [comment]
@RainyXeon 
![image](https://github.com/user-attachments/assets/ff6b6213-6630-4783-aed9-52d4e1d24dbf)
how to add button volume up and volume down

**Comment by naiserve** [comment]
I need a volume knob.
