### ISSUE TITLE
What is the main file to start the script 

### ISSUE THREAD

**Issue by NotAxiz** [RainyXeon/ByteBlaze#185]
I can't find the main file (e.g index.js or bot.js) 
Can someone help me out please

**Comment by RainyXeon** [comment]
Build the bot first `npm run build:full`
And then the main file is `src/index js`

**Comment by NotAxiz** [comment]
I'm using node js patrodyctyl panel. 
But everything is .ts
But I never seen typescript node there :(

**Comment by RainyXeon** [comment]
Try `npm run build:full && npm start`

If you can't, you have 3 methods:

Method 1: try using `npm run dev` (require more resource)

Method 2:
- Create a file named `start.sh`
- Copy this contents:
```sh
npm run build
npm run build:languages
npm run build:manifest
npm start
```
- Change start up command to `sh start.sh`
- Run node

Method 3:
- Change start up command to `npm run build:full`
- Run the your node first
- After finished, change startup command to `npm start`
- Run node again

**Comment by NotAxiz** [comment]
Bro I'm using a node js patrodyctyl panel. I don't have pc for terminal :(

**Comment by RainyXeon** [comment]
You can create file on pterodactyl when you're in web -_+

Also, what does the settings or options tab says when you're in your node?

**Comment by NotAxiz** [comment]
It much complicated... 
After every file has .ts instead of .js
![Uploading Screenshot_20240917_210940.jpg…]()

**Comment by NotAxiz** [comment]
![Uploading Screenshot_2024_0917_211035.png…]()

**Comment by NotAxiz** [comment]
Can I have your discord I'd...there will be better

**Comment by RainyXeon** [comment]
> Can I have your discord I'd...there will be better

rainyxeon

**Comment by RainyXeon** [comment]
> Can I have your discord I'd...there will be better

So you're first time using TS, ic. Maybe newbie ig so

**Comment by NotAxiz** [comment]
Yes usually I use javascript. So, i think it's also js.
But I have never found node for typescript in any host

**Comment by RainyXeon** [comment]
> Can I have your discord I'd...there will be better

But yeah, I can only face to face support u only on 15:45 (+7 timezone) so yeah ┐⁠(⁠ ⁠∵⁠ ⁠)⁠┌. I can't support you more currently
