### ISSUE TITLE
Play command via prefix

### ISSUE THREAD

**Issue by neptalu0** [RainyXeon/ByteBlaze#43]
**Describe the bug**
The prefix version of play only recognizes the first arg before space i.

**To Reproduce**

1. Run prefix version play command
2. Use multiword song
3. ie. *!p rise up thefatrat*

**Expected behavior**
My defaultSearchEngine is set to YT Music, so an audio of `Rise Up - TheFatRat` is expected, but a track only titled `Rise` gets queued instead

**Screenshots and logs (logs file if avalible)**

![Screenrecorder-2024-02-10-11-29-32-231-ezgif com-video-to-gif-converter](https://github.com/RainyXeon/ByteBlaze/assets/43881378/002b7208-2071-4806-9e79-8074c65200ae)

**Bot info (use `/info` command and paste here, below is example):**

```
Codename        | vocaloid_kaito
Bot Version     | 5.0.0
Node.js         | v21.6.1
Discord.js      | 14.13.0
Autofix Version | 5.0.0
Guild Count     | 13
User Count      | 3002
```

**Comment by neptalu0** [comment]
i figured it would work by encasing it in `"` but if theres a way not to, it'd be appreciated

**Comment by RainyXeon** [comment]
#44

**Comment by neptalu0** [comment]
Cheers! This worked too well!
