### ISSUE TITLE
Insert a song into the current queue

### ISSUE THREAD

**Issue by Cold-EA** [RainyXeon/ByteBlaze#49]
Hello,

I would like a feature where I can "Insert" a song into the current queue.
Where I can add a song as the NEXT SONG to play in the queue, without disrupting or clearing the current queue.

Example:
Normal queue: Song 1, Song 2, Song 3, Song 4
... after using the insert command to add a song: Song 5, Song 1, Song 2, Song 3, Song 4

Thanks In Advanced

**Comment by RainyXeon** [comment]
Planned! Will work at 5.1.x release

**Comment by RainyXeon** [comment]
Now done in df612399bff07e7aea544fa865a7274c3373fb29 (dev commit)
Keep in mind that this feature right now will only available in dev branch
If you want to use that , please change to dev channel by using all this command:
```
git pull
git switch dev
```  

If you have error at using 2 command above, try these command:
```
git reset --hard HEAD
git pull
git switch dev
```
