### ISSUE TITLE
Unable to use /play from other channels?

### ISSUE THREAD

**Issue by fmunim** [RainyXeon/ByteBlaze#54]
**Describe the bug**
Lets say I am on a text only channel and when I type /play <song> the bot should join my voice channel that I am in and start playing but it is not doing that. Keep saying `⚠️ | I do not have Speak permission to execute this command!` When they have all the permission. This works only on the voice channels text channel.

**To Reproduce**
Go to any text channel with / support enabled and join a voice channel, Try playing and it should give that error.

**Expected behavior**
Join VC and start playing the song 

**Bot info (use `/info status` command and paste here, below is example):**

Codename        | vocaloid_kaito
Bot Version     | 5.0.8
Node.js         | v21.7.1
Discord.js      | 14.13.0
Autofix Version | 5.0.1
Guild Count     | 1
User Count      | 2730

**Comment by RainyXeon** [comment]
Are u tick the Administrator permission in bot role instead of giving manually? If yes, can u check if that voice that bot join have Speak permission for bot? If no, can u enable the speak permission in bot role manually?

**Comment by fmunim** [comment]
> Are u tick the Administrator permission in bot role instead of giving manually? If yes, can u check if that voice that bot join have Speak permission for bot? If no, can u enable the speak permission in bot role manually?

Well that worked, but the problem is--isn't this a very permission to give? I have already checked all the voice permission but unless its given `Administrator` it keep saying that message.

**Comment by RainyXeon** [comment]
@fmunim 
In v5, I make a strict permission checker so I can avoid bot error when missing permission.
Ig I won't allow bypass all check using `Administrator` permission in the future.
So until v6 or v6.1, u have to enable `Speak` permission manually, not by using `Administrator`

**Comment by fmunim** [comment]
> @fmunim 
> 
> In v5, I make a strict permission checker so I can avoid bot error when missing permission.
> 
> Ig I won't allow bypass all check using `Administrator` permission in the future.
> 
> So until v6 or v6.1, u have to enable `Speak` permission manually, not by using `Administrator`
> 
> 

Nice! I will just work with `Administrator` permission till then. `Speak` permission doesn't work.

**Comment by RainyXeon** [comment]
@fmunim Wait, u have to enable `Administrator` to run the bot? Can u just enable all this permission only?
![image](https://github.com/RainyXeon/ByteBlaze/assets/86668725/92b262c4-c349-4cd2-8fd6-316b58e93c5e)

**Comment by fmunim** [comment]
> @fmunim Wait, u have to enable `Administrator` to run the bot? Can u just enable all this permission only?
> 
> ![image](https://github.com/RainyXeon/ByteBlaze/assets/86668725/92b262c4-c349-4cd2-8fd6-316b58e93c5e)
> 
> 

I tried but still was giving me the error. Unless I give `Administrator` it will keep giving that error.

**Comment by RainyXeon** [comment]
@fmunim can u check if that voice is private or not

**Comment by fmunim** [comment]
> @fmunim can u check if that voice is private or not

It's public, not private

**Comment by RainyXeon** [comment]
@fmunim Hmm... so weird, can u make sure u not attach any role that have voice permission disabled? Bc any bot have normal with this. I'm not sure that u're disable any permission in bot role and attached role or not?

**Comment by fmunim** [comment]
> @fmunim Hmm... so weird, can u make sure u not attach any role that have voice permission disabled? Bc any bot have normal with this. I'm not sure that u're disable any permission in bot role and attached role or not?

Okay I tried that but still same error, sadly.

**Comment by RainyXeon** [comment]
@fmunim Can u try invite [my bot](https://discord.com/api/oauth2/authorize?client_id=992776455790534667&permissions=139657014608&scope=applications.commands%20bot) (ByteBlaze based) and try to use it to make sure that problem is from your server or not?

**Comment by fmunim** [comment]
> @fmunim Can u try invite [my bot](https://discord.com/api/oauth2/authorize?client_id=992776455790534667&permissions=139657014608&scope=applications.commands%20bot) (ByteBlaze based) and try to use it to make sure that problem is from your server or not?

Same thing sadly. 
<img width="512" alt="Hmm" src="https://github.com/RainyXeon/ByteBlaze/assets/32178410/a6e993e3-7323-4b57-b2f8-546de3f9f734">

**Comment by fmunim** [comment]
32178410/d0774de0-a141-4732-9a77-09a0a147c314">


> @fmunim I just updated to v5.0.12 in dev branch, this version have ability to return missing permission error with channel mention if it have. Can u try to run this version [1fc019b](https://github.com/RainyXeon/ByteBlaze/commit/1fc019b181d8510db0abe5b203f9e4fdd41dca90) and use /play command to see which channel that bot missing permission?

Same stuff, I have made sure all the permissions are good
<img width="598" alt="Screen Shot 2024-03-12 at 10 06 21 AM" src="https://github.com/RainyXeon/ByteBlaze/assets/

**Comment by RainyXeon** [comment]
@fmunim Can I get your discord username so I can talk with u more easily. Maybe I found your problem but this is weird when text channel needs the permission

**Comment by fmunim** [comment]
Fixed by @RainyXeon, was a channel category permission thing
