### ISSUE TITLE
Eval Command + YouTube Support but YouTube can't give Ban

### ISSUE THREAD

**Issue by CPS7** [RainyXeon/ByteBlaze#75]
Please can you make a Eval Command, which can eval any Javascript code without full bot code or any client like it can evaluate codes like message.channel.send("Hi") .

And Like YouTube is giving ban to bots supporting YouTube, so can you do like if any one paste URL or search anything ,so the bot should search on YouTube and than take the track and searches it on other platforms and then play with that and if the result not found the song then the bot should play from YouTube then the chances of ban will get low.

**Comment by RainyXeon** [comment]
@CPS7 YouTube Support but YouTube can't give Ban now avaliable on https://github.com/RainyXeon/ByteBlaze/commit/66ffc5628bd7ced427459f425e9c6837cf5a4e0f

Source: https://github.com/RainyXeon/ByteBlaze/tree/66ffc5628bd7ced427459f425e9c6837cf5a4e0f

Check: [/src/structures/Rainlink.ts#L46-L51](https://github.com/RainyXeon/ByteBlaze/blob/66ffc5628bd7ced427459f425e9c6837cf5a4e0f/src/structures/Rainlink.ts#L46-L51) to see how to add more source

**Comment by CPS7** [comment]
Thanks
