### ISSUE TITLE
Getting Error and bot not responding

### ISSUE THREAD

**Issue by CPS7** [RainyXeon/ByteBlaze#76]
So what happens is the bot works perfectly for sometime then i get this prompt and the bot stops working
Possible AsyncEventEmitter memory leak detected. 11 closed listeners added to WebSocketShard. Use emitter.setMaxListeners() to increase the limit.

**Comment by RainyXeon** [comment]
Can you describe more using this form?
- How can you reproduce it?
- What's your current bot information? (Use /info command)
- What's current resources usage in that time?
- Do you have a screenshot or log file? (If yes, send me here)

**Comment by CPS7** [comment]
> Can you describe more using this form?
> 
>  it start happening itself
> Codename        | BOB
   Bot Version     | 1.0.0
   Node.js         | v20.11.0
   Discord.js      | 14.14.1
   Autofix Version | 1.0.0
   Guild Count     | 7
   User Count      | 463
> Cpu 21% (self hosted on vs code)
> ![byteblaze log - BOB THE BOT - Visual Studio Code 08-04-2024 21_23_29](https://github.com/RainyXeon/ByteBlaze/assets/149692687/4704d42a-dd51-482b-8660-0afaced85f15)

**Comment by RainyXeon** [comment]
@CPS7 can I get a full byteblaze.log file?

**Comment by CPS7** [comment]
[byteblaze.log](https://github.com/RainyXeon/ByteBlaze/files/14908065/byteblaze.log)

**Comment by RainyXeon** [comment]
@CPS7 Can u try this new hotfix?
https://github.com/RainyXeon/ByteBlaze/tree/35313141e090c43ddba4daa0e88de68809fd5d67

**Comment by CPS7** [comment]
ok

**Comment by CPS7** [comment]
i think got fixed Thanks

**Comment by RainyXeon** [comment]
@CPS7 Can u also check the case that lavalink disconnect and reconnect several times?

**Comment by CPS7** [comment]
hmm also i am getting error if i connect bot to and turn on 24/7 then this error shows up
 manager.js             - Error: The voice connection is not established in 15000ms
    at RainlinkVoiceManager.<anonymous> (file:///C:/Users/g9873/OneDrive/Desktop/BOB%20THE%20BOT/dist/rainlink/Manager/RainlinkVoiceManager.js:66:27)
    at Generator.throw (<anonymous>)
    at rejected (file:///C:/Users/g9873/OneDrive/Desktop/BOB%20THE%20BOT/dist/rainlink/Manager/RainlinkVoiceManager.js:7:65)
    
    
  and this came back 
  Possible AsyncEventEmitter memory leak detected. 11 error listeners added to WebSocketShard. Use emitter.setMaxListeners() to increase the limit.
Possible AsyncEventEmitter memory leak detected. 11 ready listeners added to WebSocketShard. Use emitter.setMaxListeners() to increase the limit.

**Comment by RainyXeon** [comment]
@CPS7 Xan U get a new full log?

Also about the 247 one, do u use that command without inside the voice?

**Comment by CPS7** [comment]
when i used i was in the vc but i left and after sometime this issue came

**Comment by CPS7** [comment]
[Uploading byteblaze.log…]()

**Comment by CPS7** [comment]
[byteblaze.log](https://github.com/RainyXeon/ByteBlaze/files/14908619/byteblaze.log)

**Comment by RainyXeon** [comment]
> when i used i was in the vc but i left and after sometime this issue came

I can't reproduce that one. Leave this later. Maybe can u make sure that u have cloned ByteBlaze on dev branch?

**Comment by CPS7** [comment]
ohh ok
