### ISSUE TITLE
Youtube link

### ISSUE THREAD

**Issue by NotApex** [RainyXeon/ByteBlaze#80]
**Describe the bug**
If you paste a YouTube link with a tracking query at the end the bot wont register it as a youtube link and you have to remove the tracking query https://youtu.be/dQw4w9WgXcQ?si=i-KNtwB8Bzy6Q4IY 

**To Reproduce**

1. Go to 'https://youtu.be/dQw4w9WgXcQ'
2. Click on 'share'
3. Click on 'copy'
4. Open discord type '/play search: https://youtu.be/dQw4w9WgXcQ?si=i-KNtwB8Bzy6Q4IY'
5. see error

**Comment by NotApex** [comment]
Forgot to add Bot info
Codename        | vocaloid_kaito
Bot Version     | 5.1.5
Node.js         | v21.7.2
Discord.js      | 14.14.1
Autofix Version | 5.1.0

**Comment by RainyXeon** [comment]
@NotApex Idk why u can't use this type of link even though I tried it and it still works. So I'll tag this "unverified". Also, can u give me more information about what the bot replies when using this link?

**Comment by NotApex** [comment]
Idk I just tried it and it worked I got a no song error when it originally happend
