### ISSUE TITLE
MAX Length for a song

### ISSUE THREAD

**Issue by en0o0n** [RainyXeon/ByteBlaze#86]
**Is your feature request related to a problem? Please describe.**
Songs Length no limit

**Describe the solution you'd like**
For example, if there is a command to set max length 
So after setting up the length to 8 min 
Thats must skip the playing song automatically if its more than 8 minutes long.

**Comment by RainyXeon** [comment]
@en0o0n Does it will remove all the track more than 8 minutes in the queue after run the command?

**Comment by en0o0n** [comment]
@RainyXeon  Thats really good question

I was thinking of two possibilities:
To merge max-length inside the script
First Method:
1. The song can play normally but it should skip automatically to next song in the queue if the max-length reached 
Second Method:
2. Or if its easier when the command "set max-length 8 minute enabled" then it must ignore every songs more than 8 minutes



BTW i have an issue with "autoplay" command (Shall i open new issue for it?)
Cause i tried to play a song then i enable autoplay 
Usually it must play me random songs right? But after my requested song finish, the music doesnt play any random song.

**Comment by RainyXeon** [comment]
@en0o0n Can I get your song link? Bc I just see some src contains japanese, korean, chinese cannot search on lavalink

**Comment by en0o0n** [comment]
@RainyXeon Im sorry i didnt understand. Which song link do you mean?

**Comment by RainyXeon** [comment]
@en0o0n like the song link that you have autoplay issue.

**Comment by en0o0n** [comment]
it must be a link?
I just tried this:

> d! play indila
The song started to play
> d! autoplay 
The autoplay is enabled

But after the song finished, the queue stayed empty and didnt played any random music.

Am i doing it wrong?

**Comment by RainyXeon** [comment]
@en0o0n ok so which version/branch are you in?

**Comment by en0o0n** [comment]
Where can i see the branch version?

Well these what i did 
i cloned the repo https://github.com/RainyXeon/ByteBlaze.git
run npm i
run npm run build:full
run npm start

I have node version v18.20.2
byteblaze@1.0.0 build:manifest

**Comment by RainyXeon** [comment]
@en0o0n Can you go to my discord server (check README.md), test my bot and tell more after that?

My bot is on dev branch so I wonder if lavalink doesn't support hindi characters
