### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'D:\ByteBlaze\app.yml'

### ISSUE THREAD

**Issue by bimaindrawans** [RainyXeon/ByteBlaze#91]
i got error Error: ENOENT: no such file or directory, open 'D:\ByteBlaze\app.yml', but the problem is, i already created that app.yml from example full app yml

![image](https://github.com/RainyXeon/ByteBlaze/assets/147312348/ad9f5f23-e33c-4cd8-b6b6-eb1d165a3f70)

**Comment by RainyXeon** [comment]
@bimaindrawans Can you do `ls` to check if file exist in msys2?

**Comment by bimaindrawans** [comment]
> @bimaindrawans Can you do `ls` to check if file exist in msys2?

ooohh i'm sorry, i found it, it was my server that got error, everything that i save on that server will generate as .txt file even if i using all files type, but i found another problem when success to save it on .yml file
> byteblaze@1.0.0 start
> node ./dist/index.js


file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:1273
  return new exception(message, mark);
         ^
YAMLException: bad indentation of a mapping entry (25:47)

 22 |  ... 't have or don't want, you can disable it
 23 |  ...
 24 |  ... 85bbe4f8c9110742ef86133dd"
 25 |  ... cd438f2344b5980ee5859c04fdae7""
-----------------------------------------^
 26 |  ...
 27 |  ... ch suggestion for auto complete, leave it empty will use default
    at generateError (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readDocument (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///D:/ByteBlaze/node_modules/js-yaml/dist/js-yaml.mjs:2778:5) {
  reason: 'bad indentation of a mapping entry',
  mark: {
    name: null,
    buffer: '# ByteBlaze config file via .yml\r\n' +
      '# Version 5.0.0\r\n' +
      '# You can use undefined to pass an enviroment varible from .env file\r\n' +
      '# Eg:\r\n' +
      '# something: undefined\r\n' +
      '\r\n' +
      'bot:\r\n' +
      '  TOKEN: "MTIxOTQwMzE0NTk2NTIxMTY5OQ.GS-UqA.SDkucONzgEm4hmbboOCLr1ncL4RA0I9qQC2W1c"\r\n' +
      '  EMBED_COLOR: "#2B2D31"\r\n' +
      '  OWNER_ID: "1158760489015320647"\r\n' +
      '  ADMIN: ["791416346646675516"]\r\n' +
      '  LANGUAGE: "en" # You can set it to en, vi...\r\n' +
      '  LIMIT_TRACK: 150 # The number of tracks you want to limit\r\n' +
      '  LIMIT_PLAYLIST: 50 # The number of playlist you want to limit\r\n' +
      "  SAFE_ICONS_MODE: false # If the new icon doesn't appear, try changing this to true\r\n" +
      '  DELETE_MSG_TIMEOUT: 3000\r\n' +
      '  DEBUG_MODE: false\r\n' +
      '\r\n' +
      'lavalink:\r\n' +
      '  SPOTIFY:\r\n' +
      '    # Your Spotify ID and Secret, you can get it from here: https://developer.spotify.com\r\n' +
      "    # If you don't have or don't want, you can disable it\r\n" +
      '    enable: true\r\n' +
      '    id: "db8101585bbe4f8c9110742ef86133dd"\r\n' +
      '    secret: "d1bcd438f2344b5980ee5859c04fdae7""\r\n' +
      '\r\n' +
      '  # Default search suggestion for auto complete, leave it empty will use default\r\n' +
      '  AUTOCOMPLETE_SEARCH: ["yorushika", "yoasobi", "tuyu", "hinkik"]\r\n' +
      '\r\n' +
      '  NP_REALTIME: true # Enable this if you want to use realtime duation in nowplaying command\r\n' +
      '\r\n' +
      '  LEAVE_TIMEOUT: 60000 # The number of leave time you want\r\n' +
      '\r\n' +
      '  DEFAULT_VOLUME: 100 # Must not over 1000 or bot crash\r\n' +
      '\r\n' +
      '  # Enable this to avoid your bot get suspended (Recommended to be enable)\r\n' +
      '  AVOID_SUSPEND: true\r\n' +
      '\r\n' +
      '  # You can add more Lavalink servers!\r\n' +
      '  NODES:\r\n' +
      '    - host: "lavalink.oryzen.xyz"\r\n' +
      '      port: 80 # Your host port here\r\n' +
      '      name: "Dayat Lavalink" #only a-z A-Z 0-9 and _\r\n' +
      '      auth: "oryzen.xyz"\r\n' +
      '      secure: false\r\n' +
      '      # In rainlink, it support lavalink v3, lavalink v4 and nodelink v2 as driver\r\n' +
      '      # If you put the wrong driver identify here or not put anything here,\r\n' +
      '      # it will fallback to lavalink v4 driver\r\n' +
      '      # Driver identify and support range:\r\n' +
      '      # | Type     | Support versions | Driver Name       |\r\n' +
      '      # | -------- | ---------------- | ----------------- |\r\n' +
      '      # | Lavalink | v4.0.0 - v4.x.x  | lavalink/v4/koinu |\r\n' +
      '      # | Lavalink | v3.0.0 - v3.7.x  | lavalink/v3/koto  |\r\n' +
      '      # | Nodelink | v2.0.0 - v2.x.x  | lavalink/v3/koto  |\r\n' +
      '      driver: "lavalink@4"\r\n' +
      '\r\n' +
      'features:\r\n' +
      '  # Enable debug tools for execute code from bot\r\n' +
      '  # use dokdo package, owner only, no prefix changes\r\n' +
      '  # You have to enable message_content to use\r\n' +
      '  # use: sudo rdc help, for more command\r\n' +
      '  DEBUG_TOOLS: true\r\n' +
      '  # Log register premium activities\r\n' +
      '  PREMIUM_LOG_CHANNEL: ""\r\n' +
      '  # Log all the guild that bot joined or leaved\r\n' +
      '  GUILD_LOG_CHANNEL: ""\r\n' +
      '  # Log all unhandled, error, warnings on discord\r\n' +
      '  LOG_CHANNEL: ""\r\n' +
      '\r\n' +
      '  DATABASE:\r\n' +
      '    # Note: If you enter an invalid driver, bot will use json driver as default\r\n' +
      '    driver: "json" # mongodb, mysql, json, postgres\r\n' +
      '    # Config depends on driver, you can see sample config at src/database/driver\r\n' +
      '    config: { path: "./cylane.database.json" }\r\n' +
      '\r\n' +
      '  MESSAGE_CONTENT:\r\n' +
      '    enable: true\r\n' +
      '    commands:\r\n' +
      '      enable: true\r\n' +
      '      prefix: "d." # The prefix you want\r\n' +
      '\r\n' +
      '  AUTOFIX_LAVALINK: # Fix the Lavalink server when the current is down\r\n' +
      '    enable: true\r\n' +
      '    retryCount: 10\r\n' +
      '    retryTimeout: 3000\r\n' +
      '\r\n' +
      '  WEB_SERVER:\r\n' +
      '    enable: false\r\n' +
      '    port: 3000\r\n' +
      '    whitelist: [] # Example: ["lavalink.dev"]\r\n' +
      '    auth: "youshallnotpass"\n',
    position: 931,
    line: 24,
    column: 46,
    snippet: " 22 |  ... 't have or don't want, you can disable it\n" +
      ' 23 |  ... \n' +
      ' 24 |  ... 85bbe4f8c9110742ef86133dd"\n' +
      ' 25 |  ... cd438f2344b5980ee5859c04fdae7""\n' +
      '-----------------------------------------^\n' +
      ' 26 |  ... \n' +
      ' 27 |  ... ch suggestion for auto complete, leave it empty will use default'
  }
}

Node.js v20.13.1

**Comment by RainyXeon** [comment]
@bimaindrawans You have one extra double quote on the last of line 25 in `app.yml` file, please delete it

**Comment by bimaindrawans** [comment]
> @bimaindrawans You have one extra double quote on the last of line 25 in `app.yml` file, please delete it

worked, thankyou sooo much
