### ISSUE TITLE
Yt Playlist support

### ISSUE THREAD

**Issue by CPS7** [RainyXeon/ByteBlaze#92]
Need support that user can import youtube playlist in queue

**Comment by RainyXeon** [comment]
@CPS7 Huh, wdym? I thought I was supported before?
![image](https://github.com/RainyXeon/ByteBlaze/assets/86668725/f45e5280-458e-4213-9962-46b6b783fe83)

**Comment by CPS7** [comment]
Why mine saying no songs found

**Comment by CPS7** [comment]
https://youtube.com/playlist?list=RDEMivmOjajBbYvKJvQj4BrVdw&playnext=1&si=VIgwAotr6stncMm1
Try this one its public

**Comment by RainyXeon** [comment]
@CPS7 I tried and yeah, It can play

![Screenshot_20240516-171136_Discord.png](https://github.com/RainyXeon/ByteBlaze/assets/86668725/14c3cbd6-9871-40e3-9e0f-e8a173e6d13f)

**Comment by CPS7** [comment]
Ohh sorry i checked lavalink it is showing error for this specific playlist sorry issue from my side

**Comment by CPS7** [comment]
Sorry one again closing this issue

**Comment by RainyXeon** [comment]
@CPS7 No problem
